// Code generated by "mapstructure-to-hcl2 -type Communicator"; DO NOT EDIT.
package winrm

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatCommunicator is an auto-generated flat version of Communicator.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatCommunicator struct {
}

// FlatMapstructure returns a new FlatCommunicator.
// FlatCommunicator is an auto-generated flat version of Communicator.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Communicator) FlatMapstructure() interface{} { return new(FlatCommunicator) }

// HCL2Spec returns the hcl spec of a Communicator.
// This spec is used by HCL to read the fields of Communicator.
// The decoded values from this spec will then be applied to a FlatCommunicator.
func (*Communicator) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{}
	return s
}
